### ISSUE TITLE
CSGO Lan Club

### ISSUE THREAD

**Issue by raddzz** [alexhemming/Ada-Clubs#1]
Yahye, Aadil, Wares, Akhil, James

**Comment by raddzz** [comment]
# Vision statement


I’m working with ADA college to make a CSGO club so that the students of ADA can get people better at CSGO, maybe compete in UK leagues and bigger LANs. Meet new people that share the same interests. Build stronger relationships and have more in common with people you thought you would not have known.

**Comment by Yahye-Abdulle** [comment]
I strongly agree with this club concept.

**Comment by MuhammadArr01** [comment]
I personally disagree.

**Comment by raddzz** [comment]
> I personally disagree.

you are being a problem

**Comment by alexhemming** [comment]
I'm merging this club with the LAN Gaming club
