### ISSUE TITLE
Anime Debate Club

### ISSUE THREAD

**Issue by Doanhluunguyen** [alexhemming/Ada-Clubs#4]
Alexander Emerson-Arfstromn
Josh
Raheem
Doanh

**Comment by Doanhluunguyen** [comment]
Initial Ideas
Josh
Raheem

Contributors

Alexander Emerson
Doanh

**Comment by Doanhluunguyen** [comment]
We are working with ada students ( Josh, Alexander Emerson Arfstrom, Doanh and Raheem) and are aiming for a sponsor to help our heated arguments.
What you’re doing
We’re debating about anime
Who you’re doing it for, your audience (may be same as the previous question)
		Anime lovers
Why you’re doing this, the impact or change you hope to make
To be able to create arguments based off on facts and what we have seen. Can be useful in generating ideas and what is good and not.

**Comment by alexhemming** [comment]
I'm merging this club with the Japanese Culture Club.
